# This file was generated by GoReleaser. DO NOT EDIT.
cask "convertr" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "4e6669a6d1ef254216b596099864c17598e31fbedfc90a3f2a3d65e1ad861e0f"
      url "https://github.com/mark1708/convertr/releases/download/v#{version}/convertr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b48bc11c780bc1062c6517914155d0094cd610b737c81f1d70b8757974d498fa"
      url "https://github.com/mark1708/convertr/releases/download/v#{version}/convertr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "265c6516b13e7fe8a12f6bf086b2c811dc5c558b5243146a85477c42e3b3af2e"
      url "https://github.com/mark1708/convertr/releases/download/v#{version}/convertr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e33147a33eb61f4437c8b1ab080f2045b95ae60961f9cf2014b1de0582b4de2e"
      url "https://github.com/mark1708/convertr/releases/download/v#{version}/convertr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "convertr"
  desc "Universal file format converter CLI"
  homepage "https://github.com/Mark1708/convertr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "convertr"

  # No zap stanza required

end
