# This file was generated by GoReleaser. DO NOT EDIT.
cask "convertr" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "68f40e8f985223e18b45320182fdf74a1cbd27a84fa437d01da042ccacd1402d"
      url "https://github.com/mark1708/convertr/releases/download/v#{version}/convertr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "40bbda92a34870f969dbb720053850e4efe690e4dd9b9c23efe25b8da7c32f73"
      url "https://github.com/mark1708/convertr/releases/download/v#{version}/convertr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7e57cac4459f935e5ecd4e96a225e2b95befb56a4bd55ceced7a345cecea18be"
      url "https://github.com/mark1708/convertr/releases/download/v#{version}/convertr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d02f1b1fca9b5e0a238efa5fcdb90913e02d801b04c33c26bd551c0e63b58276"
      url "https://github.com/mark1708/convertr/releases/download/v#{version}/convertr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "convertr"
  desc "Universal file format converter CLI"
  homepage "https://github.com/Mark1708/convertr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "convertr"

  # No zap stanza required

end
