# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmh" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "d3d964a329a8fdc32177f91663c9f1e3c7bfe730982dd5bd26d7139514b5d057"
      url "https://github.com/Mark1708/tmh/releases/download/v#{version}/tmh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "35fd9a5a09c14ea6c8ddf61db82db232ad1acd1e0e55da77fd79fef12b82feba"
      url "https://github.com/Mark1708/tmh/releases/download/v#{version}/tmh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8df18a8aeb8e992a8f84c53279b5f26eb57bdf6a5a4030c3cf98f51326c686b5"
      url "https://github.com/Mark1708/tmh/releases/download/v#{version}/tmh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "80b61736032df74817201baf6b7cdcd9da52ccfad9662db613ac3e46eeac812e"
      url "https://github.com/Mark1708/tmh/releases/download/v#{version}/tmh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tmh"
  desc "Declarative tmux session manager with drift detection and dotfile reload"
  homepage "https://github.com/mark1708/tmh"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "tmh"
  manpage "docs/generated/man/tmh.1"
  bash_completion "docs/generated/completions/bash/tmh"
  fish_completion "docs/generated/completions/fish/tmh"
  zsh_completion "docs/generated/completions/zsh/tmh"

  # No zap stanza required

end
